name: Go

on: [push]

env:
  REGISTRY: ghcr.io
  PLATFORMS: amd64

jobs:
  test-build-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Install and initialize dependencies
        run: go get .
      - name: Unit test
        run: go test -v .
